OurWork/Controllers/ApplianceController.cs
using OurWork.Models;
using OurWork.Enums;
using OurWork.Repository;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace OurWork.Controllers
{
    public class ApplianceController : Controller
    {
        private const int DEFAULT_APPLIANCE_ABILITIES = 2;
        private readonly JobAppliancesRepository _appRepository;
        private readonly UserRepository _userRepository;
        private readonly SkillsRepository _skillsRepository;
        private readonly SkillAttributesRepository _skillAttrsRepository;
        private readonly AbilitiesRepository _abilRepository;
        private readonly AbilitySetsRepository _abilSetRepository;

        public ApplianceController()
        {
            _appRepository = new JobAppliancesRepository();
            _userRepository = new UserRepository();
            _skillsRepository = new SkillsRepository();
            _skillAttrsRepository = new SkillAttributesRepository();
            _abilRepository = new AbilitiesRepository();
            _abilSetRepository = new AbilitySetsRepository();
        }

        public ActionResult Index()
        {
            UserProfile currentUser = GetCurrentUser();

            if (currentUser.RoleId != (int)UserRoleTypes.Applicant)
            {
                return Redirect("/Home/Index");
            }

            IEnumerable<JobAppliance> userAppliances = _appRepository.GetByUserId(currentUser.UserId);

            return View(userAppliances);
        }

        public ActionResult NewAppliance()
        {
            UserProfile currentUser = GetCurrentUser();

            if (currentUser.RoleId != (int)UserRoleTypes.Applicant)
            {
                return Redirect("/Home/Index");
            }                       

            List<SelectListItem> skills = _skillsRepository.GetAll().
                        Select(r => new SelectListItem { Value = r.Id.ToString(), Text = r.SkillName }).
                        ToList();            

            List<SelectListItem> skillLevels = _skillsRepository.GetSkillLevels().
                        Select(r => new SelectListItem { Value = r.Id.ToString(), Text = r.ValueName }).
                        ToList();            

            List<SelectListItem> skillAttributes = _skillAttrsRepository.GetAll().
                        Select(r => new SelectListItem { Value = r.Id.ToString(), Text = r.Name }).
                        ToList();

            CreateApplianceModel dataModel = new CreateApplianceModel();

            for (int i = 0; i < DEFAULT_APPLIANCE_ABILITIES; i++)
            {
                Ability ability = new Ability();
                dataModel.ApplianceAbilities.Add(ability);
            }

            ViewBag.Skills = skills;
            ViewBag.SkillLevels = skillLevels;
            ViewBag.SkillAttributes = skillAttributes;

            return View(dataModel);
        }

        [HttpPost]
        public ActionResult CreateAppliance(CreateApplianceModel data)
        {
            //Adding new appliance
            JobAppliance newAppliance = new JobAppliance();

            newAppliance.Name = data.ApplianceData.Name;
            newAppliance.Comment = data.ApplianceData.Comment;
            newAppliance.UserId = GetCurrentUser().UserId;

            if (!_appRepository.Create(newAppliance))
            {                
                return RedirectToAction("/Error/Index");
            }

            _appRepository.Save();

            int newAppId = newAppliance.Id;

            //Adding abilities and ability set for new appliance
            foreach (Ability ability in data.ApplianceAbilities)
            {                
                Ability newAbilities = new Ability();

                newAbilities.SkillId = ability.SkillId;
                newAbilities.SkillLevelId = ability.SkillLevelId;
                
                if (!_abilRepository.Create(newAbilities))
                {
                    return RedirectToAction("/Error/Index");
                }

                _abilRepository.Save();

                int newAbilId = newAbilities.Id;
                
                AbilitySet newAbilitySet = new AbilitySet();

                newAbilitySet.ApplianceId = newAppliance.Id;
                newAbilitySet.AbilitiesId = newAbilities.Id;

                if (!_abilSetRepository.Create(newAbilitySet))
                {
                    return RedirectToAction("/Error/Index");
                }

                _abilSetRepository.Save();
            }

            return RedirectToAction("Index");
        }

        private UserProfile GetCurrentUser()
        {
            return _userRepository.GetByName(User.Identity.Name);
        }
    }
}

OurWork/Views/Appliance/Index.cshtml
@using OurWork.Models
@model IEnumerable<OurWork.Models.JobAppliance>
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="p-3">
        <h2>My appliances</h2>
    </div>
    <div class="p-4">
        @Html.ActionLink("Add Appliance", "NewAppliance", "Appliance",
                routeValues: null,
                htmlAttributes: new { @class = "btn btn-success btn-large" })
    </div>
</div>


@if (Model.Any())
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    Name
                    
                </th>
                <th>
                    Comment
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (JobAppliance item in Model)
            {
                <tr>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Comment
                    </td>
                </tr>
            }
        </tbody>
    </table>
    
    
    
}

OurWork/Views/Appliance/NewAppliance.cshtml
@model OurWork.Models.CreateApplianceModel
@using OurWork.Models

@{
    ViewBag.Title = "NewAppliance";
    List<SelectListItem> skills = ViewBag.Skills;
    List<SelectListItem> skillLevels = ViewBag.SkillLevels;
}

<h2>New Appliance</h2>

@using (Html.BeginForm("CreateAppliance", "Appliance"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    
    <h3>Appliance Info</h3>
    
    <div class="form-group">
        @Html.LabelFor(m => m.ApplianceData.Name)
        @Html.TextBoxFor(m => m.ApplianceData.Name, htmlAttributes: new { @class = "form-control" })
    </div>
    
    <div class="form-group">
        @Html.LabelFor(m => m.ApplianceData.Comment)
        @Html.TextAreaFor(m => m.ApplianceData.Comment, htmlAttributes: new { @class = "form-control" })
    </div>
            
    <h3>Select Abilities</h3>
    
    for (int i = 0; i < Model.ApplianceAbilities.Count; i++)
    {
        <div class="form-group">
            @Html.LabelFor(m => m.ApplianceAbilities[i].SkillId)
            @Html.DropDownListFor(m => m.ApplianceAbilities[i].SkillId,
                skills, htmlAttributes: new { @class = "form-control" })
        </div>
    
        <div class="form-group">
            @Html.LabelFor(m => m.ApplianceAbilities[i].SkillLevelId)
            @Html.DropDownListFor(m => m.ApplianceAbilities[i].SkillLevelId,
                skillLevels, htmlAttributes: new { @class = "form-control" })
        </div>
    }         
        
    <input type="submit" value="Create" />
    
}