OurWork/Controllers/VacancyController.cs
using OurWork.Enums;
using OurWork.Models;
using OurWork.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;



namespace OurWork.Controllers
{
    public class VacancyController : Controller
    {
        private readonly JobOffersRepository _jobOfferRepo;
        private readonly UserRepository _userRepo;
        private readonly UserDataRepository _userDatarepo;

        public VacancyController()
        {
            _jobOfferRepo = new JobOffersRepository();
            _userRepo = new UserRepository();
            _userDatarepo = new UserDataRepository();
        }

        public ActionResult Index()
        {
            UserProfile currentUser = GetCurrentUser(); 

            if (!User.Identity.IsAuthenticated || (currentUser == null))
	        {
                return Redirect("/Account/Login");
	        }

            if (currentUser.RoleId != (int)UserRoleTypes.Company)
            {
                return Redirect("/Vacancy/WrongRole");
            }  

            int userId = GetCurrentUser().UserId;

            IEnumerable<JobOffer> offers = _jobOfferRepo.GetByUserId(userId);

            return View(offers);
        }

        public ActionResult AllVacancies()
        {
            IEnumerable<JobOffer> AllOffers = _jobOfferRepo.GetAll();

            return View(AllOffers);
        }

        public ActionResult WrongRole()
        {
           return View();
        }

        public ActionResult Vacancy(int? id)
        {
            if (id == null)
            {
                return Redirect("/Error/Index");
            }

            int vacancyId = (int)id;

            JobOffer currentOffer = _jobOfferRepo.GetById(vacancyId);            
            UserData companyData = _userDatarepo.GetByUserId(currentOffer.UserId);
            
            ViewBag.CurrentUser = GetCurrentUser();
            ViewBag.CompanyData = companyData;

            return View(currentOffer);
        }       

        private UserProfile GetCurrentUser()
        {
            return _userRepo.GetByName(User.Identity.Name);
        }

    }
}

OurWork/Views/Vacancy/AllVacancies.cshtml
@using OurWork.Models
@model IEnumerable<JobOffer>
@{
    ViewBag.Title = "AllVacanciesView";
}

<h2>AllVacanciesView</h2>

@{
    ViewBag.Title = "Index";
}

<h2>Vacancies</h2>

@if (Model != null)
{
    foreach (JobOffer v in Model)
    {
        <div>
            <p class="vacancy1">
                @v.OfferName
            </p>
            <a href="/vacancy/vacancy/@v.Id">Details</a>
        </div>
    }
}

OurWork/Views/Vacancy/Index.cshtml
@using OurWork.Models
@model IEnumerable<JobOffer>
@{
    ViewBag.Title = "Index";    
}

<h2>All your Vacancies</h2>

@if (Model != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Details
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (JobOffer v in Model)
            {
                <tr>
                    <td>
                        @v.OfferName
                    </td>
                    <td>
                        @Html.ActionLink("See Details...", "Vacancy", "Vacancy",
                            routeValues: new { id = v.Id },
                            htmlAttributes: new { @class = "btn btn-primary" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

<div class="row bottom-section" >
    <div class="col-lg-6">
        @Html.ActionLink("Add Vacancy", "Index", "CreateVacancy",
            routeValues: null,
            htmlAttributes: new { @class = "btn btn-success" })
    </div>
    <div class="col-lg-6">
        <li>
            <h5>Watch all available vacancies</h5>
            You can consider all available vacancies.
            @Html.ActionLink("Watch all vacancies", "AllVacancies", "Vacancy",
                routeValues: null,
                htmlAttributes: new { @class = "text-primary" })            
        </li>
    </div>
</div>

OurWork/Views/Vacancy/Vacancy.cshtml
@using OurWork.Enums
@using OurWork.Models
@model OurWork.Models.JobOffer

@{
    ViewBag.Title = "Vacancy";
    UserProfile currentUser = ViewBag.CurrentUser;
    UserData companyData = ViewBag.CompanyData;
}

<div class="card">
    <div class="card-header">
        Vacancy: <strong>@Model.OfferName</strong>
    </div>
    <div class="card-header">
        Company: <strong>@companyData.CompanyName</strong>
    </div>
    <div class="card-body">
        <h5 class="card-title">Vacancy Info</h5>
        <p class="card-text">@Model.OfferDescription</p>

        @if (currentUser.UserId != companyData.UserId)
        {
            <h5 class="card-title">Contacts</h5>
            <p class="card-text">Phone: @companyData.Phone</p>
            <p class="card-text">Email: @companyData.Email</p>
        }    
    </div>
</div>

<div class="bottom-section">
    @if (currentUser.RoleId == (int)UserRoleTypes.Company)
    {
        @Html.ActionLink("Search Applicants", "SearchApplicants", "Search",
        routeValues: new { id = Model.Id },
        htmlAttributes: new { @class = "btn btn-success btn-large" })
    }    
</div>

OurWork/Views/Vacancy/WrongRole.cshtml
@{
    ViewBag.Title = "WrongRole";
}

<h2>WrongRole</h2>
<div> You are logged into the system not as Recruiter</div>